### ISSUE TITLE
Infografía hilos en consola C#

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/infografia-de-hilos-Heidi-19#2]
[Infografía hilos en consola - Heidi Lucy Bautista Sanjuan 4US.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Heidi-19/files/8394715/Infografia.hilos.en.consola.-.Heidi.Lucy.Bautista.Sanjuan.4US.pdf)

**Comment by JudithReynaCS** [comment]
CALIFICACION:19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
